{
  "formatVersion": "1.1",
  "component": {
    "group": "com.redhat.devtools.intellij",
    "module": "intellij-common-ui-test-library",
    "version": "0.4.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "com.intellij.remoterobot",
          "module": "remote-robot",
          "version": {
            "requires": "0.11.23"
          }
        },
        {
          "group": "com.intellij.remoterobot",
          "module": "remote-fixtures",
          "version": {
            "requires": "0.11.23"
          }
        }
      ],
      "files": [
        {
          "name": "intellij-common-ui-test-library-0.4.5-SNAPSHOT.jar",
          "url": "intellij-common-ui-test-library-0.4.5-SNAPSHOT.jar",
          "size": 87625,
          "sha512": "6bd872ab5237c0dd874ffe7c90cd19f4e9a85643719e4103b593c5e3657415985c68560cc050306180ad1847c7596c8e14748e260d630d41548f82d2069e8e15",
          "sha256": "3d89ef8ebf6e106c1168e0f3e1d60afa60b043eec466446aa962b0144beaa4c3",
          "sha1": "51e71b2a171ebec796fead3bc0bc2ff10951b281",
          "md5": "fae5a2ccf98d76781e031308fd7f5a9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "com.intellij.remoterobot",
          "module": "remote-robot",
          "version": {
            "requires": "0.11.23"
          }
        },
        {
          "group": "com.intellij.remoterobot",
          "module": "remote-fixtures",
          "version": {
            "requires": "0.11.23"
          }
        }
      ],
      "files": [
        {
          "name": "intellij-common-ui-test-library-0.4.5-SNAPSHOT.jar",
          "url": "intellij-common-ui-test-library-0.4.5-SNAPSHOT.jar",
          "size": 87625,
          "sha512": "6bd872ab5237c0dd874ffe7c90cd19f4e9a85643719e4103b593c5e3657415985c68560cc050306180ad1847c7596c8e14748e260d630d41548f82d2069e8e15",
          "sha256": "3d89ef8ebf6e106c1168e0f3e1d60afa60b043eec466446aa962b0144beaa4c3",
          "sha1": "51e71b2a171ebec796fead3bc0bc2ff10951b281",
          "md5": "fae5a2ccf98d76781e031308fd7f5a9e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "intellij-common-ui-test-library-0.4.5-SNAPSHOT-sources.jar",
          "url": "intellij-common-ui-test-library-0.4.5-SNAPSHOT-sources.jar",
          "size": 65243,
          "sha512": "5128d1dbb9f2a61560fd26b197ae7fe8a3447fced50fcee01e702ed93614ec0cdc2b7d2e8c7ea6c36d1c7b0f236304ab1cef2e1ad44f4ae764d0a3e8b378a68f",
          "sha256": "0bf8cbe1f807604da81e7cfc8b2694a09e3ad6caa0d675491dfc099a89f55008",
          "sha1": "7516f1360a9a7e2a196fd0c0cd23ce16d90be6f1",
          "md5": "5372e3355ccf38cc6140e0617f2aaf39"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "intellij-common-ui-test-library-0.4.5-SNAPSHOT-javadoc.jar",
          "url": "intellij-common-ui-test-library-0.4.5-SNAPSHOT-javadoc.jar",
          "size": 302677,
          "sha512": "cbeec8e6ba2a8541c0505fa1fda8d4f8884cea9d9f28b955c976eb944b07189bbe21eab02bc156018e0aec4152aaed70f22a621d41317955f8a6ad41ce97f535",
          "sha256": "24c3bd5e67a1e69253e5707898bbd6d33429d5091b8bdff43c6d0f68ce449401",
          "sha1": "72404b10512f38ed927d564cccbdc3505acf336f",
          "md5": "a444fbb7f848bf8ac5ef22b8468d64be"
        }
      ]
    }
  ]
}
