{
  "formatVersion": "1.1",
  "component": {
    "group": "com.redhat.devtools.intellij",
    "module": "intellij-common-ui-test-library",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "com.intellij.remoterobot",
          "module": "remote-robot",
          "version": {
            "requires": "0.11.23"
          }
        },
        {
          "group": "com.intellij.remoterobot",
          "module": "remote-fixtures",
          "version": {
            "requires": "0.11.23"
          }
        }
      ],
      "files": [
        {
          "name": "intellij-common-ui-test-library-0.4.4.jar",
          "url": "intellij-common-ui-test-library-0.4.4.jar",
          "size": 95028,
          "sha512": "4d1e6032f73c095dbe809cb33a23d016191973c2befedd297f8986a583b8fc7935f940ed8524e3fbd6c66ec231a8a80a1cf35c92f23f5f3ae599497b7a8a8c78",
          "sha256": "52b0c17fab625e70598efc21763336d76bc540d3fcb96bf089f44e014a456a27",
          "sha1": "4d641251e4242d09f99dcf7b35c7def6d48a19f5",
          "md5": "14da175eec88dcdba0deae99763425d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "com.intellij.remoterobot",
          "module": "remote-robot",
          "version": {
            "requires": "0.11.23"
          }
        },
        {
          "group": "com.intellij.remoterobot",
          "module": "remote-fixtures",
          "version": {
            "requires": "0.11.23"
          }
        }
      ],
      "files": [
        {
          "name": "intellij-common-ui-test-library-0.4.4.jar",
          "url": "intellij-common-ui-test-library-0.4.4.jar",
          "size": 95028,
          "sha512": "4d1e6032f73c095dbe809cb33a23d016191973c2befedd297f8986a583b8fc7935f940ed8524e3fbd6c66ec231a8a80a1cf35c92f23f5f3ae599497b7a8a8c78",
          "sha256": "52b0c17fab625e70598efc21763336d76bc540d3fcb96bf089f44e014a456a27",
          "sha1": "4d641251e4242d09f99dcf7b35c7def6d48a19f5",
          "md5": "14da175eec88dcdba0deae99763425d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "intellij-common-ui-test-library-0.4.4-sources.jar",
          "url": "intellij-common-ui-test-library-0.4.4-sources.jar",
          "size": 68112,
          "sha512": "aaa2c1ee71867e1b0f8525907e491e3c98bbeb34105a01127905497d7d9634dd58c0641fa4c9df6261986b025bb5ac795a5741e448517b0f6540251cbbd61f44",
          "sha256": "e2102b7284dba56d42984a00c5dec0573eac40cf627d959bcf9e01975453e1e2",
          "sha1": "e738e28583ed583e60f14f9e3d3c54ffb14970b3",
          "md5": "fccca862c6f5d55eef3ee682e41d8230"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "intellij-common-ui-test-library-0.4.4-javadoc.jar",
          "url": "intellij-common-ui-test-library-0.4.4-javadoc.jar",
          "size": 315761,
          "sha512": "bbe3f7690beaff9ed8bba9b412c67b733e7b2a89aa369437e3c86cabcb33cd77214a26f7c7974420ffed1f08c49cd7a4ca114cd919f165deffbc4563a95c3cdf",
          "sha256": "e1dea8d1603954482e1bb341936345d95d649b3f6dd954477ec80fcbd0591226",
          "sha1": "9bc363ecec6af1272cb7512a2c8721e9de4dd386",
          "md5": "95e17b650cf13409c94438b4fe77a35b"
        }
      ]
    }
  ]
}
