# Main CI
name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  configure_sonar:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Save Sonar config on PR
        run: |
          mkdir -p ./prInfo
          echo ${{ github.event.number }} > ./prInfo/PR
          echo ${{ github.base_ref }} > ./prInfo/base_ref
          echo ${{ github.head_ref }} > ./prInfo/head_ref
      - uses: actions/upload-artifact@v4
        with:
          name: prInfo
          path: prInfo/

  mainidewindow_idestatusbar_screenshot:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run integration tests
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            export DISPLAY=:99.0
            Xvfb -ac :99 -screen 0 1920x1080x24 &
            cd src/test-project
            chmod +x gradlew
            ./gradlew clean integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.utils.* --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.mainidewindow.idestatusbar.*
          elif [ "$RUNNER_OS" == "Windows" ]; then
            cd src\test-project
            chmod +x gradlew.bat
            .\gradlew.bat clean integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.utils.* --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.mainidewindow.mainidewindow.idestatusbar.*
          elif [ "$RUNNER_OS" == "macOS" ]; then
            cd src/test-project
            chmod +x gradlew
            ./gradlew clean integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.utils.* --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.mainidewindow.mainidewindow.idestatusbar.*
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-mainidewindow.idestatusbar-test-reports
          path: src/test-project/build/reports/tests/test
        if: always()
      - name: Archiving screenshots
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-mainidewindow.idestatusbar-screenshots
          path: src/test-project/build/screenshots/*
        if: always()
      - name: Archiving StepLogger logs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-mainidewindow.idestatusbar-steplogger-logs
          path: src/test-project/build/test-results/*
        if: always()