# Main CI
name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  configure_sonar:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Save Sonar config on PR
        run: |
          mkdir -p ./prInfo
          echo ${{ github.event.number }} > ./prInfo/PR
          echo ${{ github.base_ref }} > ./prInfo/base_ref
          echo ${{ github.head_ref }} > ./prInfo/head_ref
      - uses: actions/upload-artifact@v4
        with:
          name: prInfo
          path: prInfo/

  run_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Set up JDK 11 # Java 11 is only used for test NewProjectDialogTest/setProjectSdkIfAvailableTest
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'
      - name: Prepare build
        run: |
          cd src/test-project
          mkdir -p build/reports
          chmod +x gradlew
      - name: Run mainidewindow_idestatusbar_screenshot integration tests
        run: xvfb-run --server-args="-screen 0 1920x1080x24" src/test-project/gradlew integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.utils.* --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.mainidewindow.idestatusbar.*
      - name: Run dialogs_information_settings integration tests
        run: xvfb-run --server-args="-screen 0 1920x1080x24" src/test-project/gradlew integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.dialogs.information.* --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.dialogs.settings.*
      - name: Run dialogs_project_manipulation integration tests
        run: xvfb-run --server-args="-screen 0 1920x1080x24" src/test-project/gradlew integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.dialogs.project_manipulation.*
      - name: Run dialogs integration tests
        run: xvfb-run --server-args="-screen 0 1920x1080x24" src/test-project/gradlew integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.dialogs.FlatWelcomeFrameTest
      - name: Run mainidewindow-menubar integration tests
        run: xvfb-run --server-args="-screen 0 1920x1080x24" src/test-project/gradlew integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.mainidewindow.menubar.*
      - name: Run mainidewindow-toolwindowspane integration tests
        run: xvfb-run --server-args="-screen 0 1920x1080x24" src/test-project/gradlew integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.mainidewindow.toolwindowspane.*
      - name: Archiving tests reports
        uses: actions/upload-artifact@v4
        with:
          name: linux-test-reports
          path: src/test-project/build/reports/tests/*
        if: always()
      - name: Archiving screenshots
        uses: actions/upload-artifact@v4
        with:
          name: linux-screenshots
          path: src/test-project/build/screenshots/*
          if-no-files-found: ignore
        if: always()
      - name: Archiving StepLogger logs
        uses: actions/upload-artifact@v4
        with:
          name: linux-steplogger-logs
          path: src/test-project/build/test-results/*
        if: always()

  run_on_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Set up JDK 11 # Java 11 is only used for test NewProjectDialogTest/setProjectSdkIfAvailableTest
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run mainidewindow_idestatusbar_screenshot integration tests
        run: src/test-project/gradlew.bat integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.utils.* --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.mainidewindow.idestatusbar.*
      - name: Run dialogs_information_settings integration tests
        run: src/test-project/gradlew.bat integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.dialogs.information.* --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.dialogs.settings.*
      - name: Run dialogs_project_manipulation integration tests
        run: src/test-project/gradlew.bat integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.dialogs.project_manipulation.*
      - name: Run dialogs integration tests
        run: src/test-project/gradlew.bat integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.dialogs.FlatWelcomeFrameTest
      - name: Run mainidewindow-menubar integration tests
        run: src/test-project/gradlew.bat integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.mainidewindow.menubar.*
      - name: Run mainidewindow-toolwindowspane integration tests
        run: src/test-project/gradlew.bat integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.mainidewindow.toolwindowspane.*
      - name: Archiving tests reports
        uses: actions/upload-artifact@v4
        with:
          name: windows-test-reports
          path: src/test-project/build/reports/tests/*
        if: always()
      - name: Archiving screenshots
        uses: actions/upload-artifact@v4
        with:
          name: windows-screenshots
          path: src/test-project/build/screenshots/*
          if-no-files-found: ignore
        if: always()
      - name: Archiving StepLogger logs
        uses: actions/upload-artifact@v4
        with:
          name: windows-steplogger-logs
          path: src/test-project/build/test-results/*
        if: always()

  run_on_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Set up JDK 11 # Java 11 is only used for test NewProjectDialogTest/setProjectSdkIfAvailableTest
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run mainidewindow_idestatusbar_screenshot integration tests
        run: src/test-project/gradlew integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.utils.* --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.mainidewindow.idestatusbar.*
      - name: Run dialogs_information_settings integration tests
        run: src/test-project/gradlew integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.dialogs.information.* --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.dialogs.settings.*
      - name: Run dialogs_project_manipulation integration tests
        run: src/test-project/gradlew integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.dialogs.project_manipulation.*
      - name: Run dialogs integration tests
        run: src/test-project/gradlew integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.dialogs.FlatWelcomeFrameTest
      - name: Run mainidewindow-menubar integration tests
        run: src/test-project/gradlew integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.mainidewindow.menubar.*
      - name: Run mainidewindow-toolwindowspane integration tests
        run: src/test-project/gradlew integrationUITest --warning-mode none --tests com.redhat.devtools.intellij.commonuitest.fixtures.test.mainidewindow.toolwindowspane.*
      - name: Archiving tests reports
        uses: actions/upload-artifact@v4
        with:
          name: macos-test-reports
          path: src/test-project/build/reports/tests/*
        if: always()
      - name: Archiving screenshots
        uses: actions/upload-artifact@v4
        with:
          name: macos-screenshots
          path: src/test-project/build/screenshots/*
          if-no-files-found: ignore
        if: always()
      - name: Archiving StepLogger logs
        uses: actions/upload-artifact@v4
        with:
          name: macos-steplogger-logs
          path: src/test-project/build/test-results/*
        if: always()
