# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle - Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run integration tests
      run: |
        export DISPLAY=:99.0
        Xvfb -ac :99 -screen 0 1920x1080x24 &
        cd src/test-project
        chmod +x gradlew
        ./gradlew clean test --warning-mode none
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-test-reports
        path: src/test-project/build/reports/tests/test
      if: always()
    - name: Archiving screenshots
      uses: actions/upload-artifact@v2
      with: 
        name: ${{ runner.os }}-screenshots
        path: src/test-project/build/screenshots/*
      if: always()
