name: Release
run-name: Release ${{ inputs.release_version }}

#Only one job at a time
concurrency: release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        type: string

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4

      # Set up Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Tag Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git commit -sam "chore(skip-release): set version to ${{ inputs.release_version }}"
          fi
          git tag ${{ inputs.release_version }}
          git push origin ${{ inputs.release_version }}

      - name: Set Release Version
        shell: bash
        run: |
          CURRENT_VERSION=$(grep "projectVersion=" gradle.properties | cut -d'=' -f2)
          NEW_VERSION=${{ inputs.release_version }}
          awk -v current="$CURRENT_VERSION" -v new="$NEW_VERSION" 'BEGIN {FS=OFS="="} $1 == "projectVersion" { $2 = new }1' gradle.properties > tmpfile && mv tmpfile gradle.properties
          echo "Release version: $NEW_VERSION"
          echo "PLUGIN_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      # Publish the plugin to local release repo
      - name: Publish Library
        run: |
          ./gradlew publish
          echo "Published $PLUGIN_VERSION."

      # Set next SNAPSHOT version
      - name: Increment Plugin Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CURRENT_VERSION=$(grep "projectVersion=" gradle.properties | cut -d'=' -f2)
          IFS="-" read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
          IFS="." read -ra VERSION_NUM <<< "${VERSION_PARTS[0]}"
          ((VERSION_NUM[2]+=1))
          NEW_VERSION="${VERSION_NUM[0]}.${VERSION_NUM[1]}.${VERSION_NUM[2]}-SNAPSHOT"
          awk -v new_version="$NEW_VERSION" '/projectVersion=/{sub(/=.*/, "=" new_version)}1' gradle.properties > tmpfile && mv tmpfile gradle.properties
          echo "Set $NEW_VERSION in gradle.properties"
          git checkout -b $NEW_VERSION
          git commit -sam "chore(skip-release): set version to $NEW_VERSION"
          git push -u origin $NEW_VERSION

      - name: Simple conventional changelog
        uses: redhat-developer/simple-conventional-changelog@0a6db1ac3910c2cf66f2e1a530951dba1ece8540 #0.0.12
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          current-tag: ${{ inputs.release_version }}
          types-mapping: 'feat:Features,fix:Bug Fixes,docs:Documentation,refactor:Refactoring,build:Build,chore:Other'

      # Create a new GitHub release
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ inputs.release_version }} \
            --title "${{ inputs.release_version }}" \
            --notes "$(cat << 'EOM'
          ${{ steps.changelog.outputs.changelog }}
          EOM
          )"

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ inputs.release_version }} ./build/distributions/*
