name: Validate against IJ versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate_versions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        IJ:
          - 2020.2
          - 2020.3
          - 2021.1
          - 2021.2
          - 2021.3
          - 2022.1
          - 2022.2
          - 2022.3
          - 2023.1
          - 2023.2
          - 2023.3
          - 2024.1
          - 2024.2
          - 2024.3

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 # Java 11 is only used for test NewProjectDialogTest/setProjectSdkIfAvailableTest
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run integration tests
        run: |
          cd src/test-project
          xvfb-run --server-args="-screen 0 1920x1080x24" ./gradlew integrationUITest --warning-mode none -PcommunityIdeaVersion=${{ matrix.IJ }}
      - name: Archiving tests reports
        uses: actions/upload-artifact@v4
        with:
          name: linux-test-reports-${{ matrix.IJ }}
          path: src/test-project/build/reports/tests/*
        if: always()
      - name: Archiving screenshots
        uses: actions/upload-artifact@v4
        with:
          name: linux-screenshots-${{ matrix.IJ }}
          path: src/test-project/build/screenshots/*
          if-no-files-found: ignore
        if: always()
      - name: Archiving StepLogger logs
        uses: actions/upload-artifact@v4
        with:
          name: linux-steplogger-logs-${{ matrix.IJ }}
          path: src/test-project/build/test-results/*
        if: always()
